# Site settings
site_name: Books
site_url: https://vivekkpatel.github.io/Books/
use_directory_urls: false

# Repository Details for "Edit on GitHub" links
repo_name: Books
repo_url: https://github.com/vivekkpatel/Books
edit_uri: edit/main/docs/

# Navigation Tree
nav:
  - Home:
    - index.md
  - Self Help:
    - Atomic Habits: Self Help/Atomic Habits.md
    - DON'T LOSE OUT, WORK OUT: Self Help/DON'T LOSE OUT, WORK OUT.md
    - Factfulness: Self Help/Factfulness.md
    - Getting Things Done: Self Help/Getting Things Done.md
    - How to Win Friends and Influence People: Self Help/How to Win Friends and Influence People.md
    - Make Time: Self Help/Make Time.md
    - Quiet The Power of Introverts: Self Help/Quiet The Power of Introverts.md
    - Show Your Work: Self Help/Show Your Work.md
    - The Obstacle Is the Way: Self Help/The Obstacle Is the Way.md
    - The Power of Habit: Self Help/The Power of Habit.md
    - The Subtle Art of Not Giving a Fuck: Self Help/The Subtle Art of Not Giving a Fuck.md
    - Thinking Fast and Slow: Self Help/Thinking Fast and Slow.md
    - Why We Sleep: Self Help/Why We Sleep.md
  - Biography:
    - Adventures of a Curious Character: Biography/Adventures of a Curious Character.md
    - Alibaba: Biography/Alibaba.md
    - Bad Blood: Biography/Bad Blood.md
    - Bricklin on Technology: Biography/Bricklin on Technology.md
    - Educated: Biography/Educated.md
    - Hard Drive: Biography/Hard Drive.md
    - Just for Fun: Biography/Just for Fun.md
    - Know My Name A Memoir: Biography/Know My Name A Memoir.md
    - Masters of Doom: Biography/Masters of Doom.md
    - My Life: Biography/My Life.md
    - My Life An Illustrated Biography: Biography/My Life An Illustrated Biography.md
    - Nikola Tesla: Biography/Nikola Tesla.md
    - Permanent Record: Biography/Permanent Record.md
    - Sam Walton Made In America: Biography/Sam Walton Made In America.md
    - Shoe Dog: Biography/Shoe Dog.md
    - Steve Jobs: Biography/Steve Jobs.md
    - The Everything Store: Biography/The Everything Store.md
    - The Glass Castle: Biography/The Glass Castle.md
    - The Upstarts: Biography/The Upstarts.md
    - When Breath Becomes Air: Biography/When Breath Becomes Air.md
    - Wild: Biography/Wild.md
  - Business:
    - Anything You Want: Business/Anything You Want.md
    - Breaking the Time Barrier: Business/Breaking the Time Barrier.md
    - Design Your Work: Business/Design Your Work.md
    - Let's Talk Money: Business/Let's Talk Money.md
    - Never Split the Difference: Business/Never Split the Difference.md
    - Rich Dad Poor Dad: Business/Rich Dad Poor Dad.md
    - The Compound Effect: Business/The Compound Effect.md
    - The Greatest Salesman in the world: Business/The Greatest Salesman in the world.md
    - The Richest Man in Babylon: Business/The Richest Man in Babylon.md
    - The Zurich Axioms: Business/The Zurich Axioms.md
    - Zero to One: Business/Zero to One.md
  - Code:
    - A Beginner's Guide to AutoHotkey: Code/A Beginner's Guide to AutoHotkey.md
    - AutoCAD 2012 DXF reference: Code/AutoCAD 2012 DXF reference.md
    - AutoCAD Platform Customization VBA: Code/AutoCAD Platform Customization VBA.md
    - AutoHotkey Applications: Code/AutoHotkey Applications.md
    - C# 8.0 in a Nutshell: Code/C# 8 0 in a Nutshell.md
    - C# in Depth: Code/C# in Depth.md
    - Clean Code: Code/Clean Code.md
    - Computational Engineering: Code/Computational Engineering.md
    - Dependency Injection in .NET: Code/Dependency Injection in NET.md
    - Digging Deeper into AutoHotkey: Code/Digging Deeper into AutoHotkey.md
    - Start Programming in NET for AutoCAD: Code/Start Programming in NET for AutoCAD.md
    - Test-Driven Development By Example: Code/Test-Driven Development By Example.md
    - The Art of Unit Testing: Code/The Art of Unit Testing With Examples in NET.md
    - The Markdown Guide: Code/The Markdown Guide.md
    - The Pragamatic Programmer: Code/The Pragamatic Programmer.md
    - Unit Testing Principles, Practices, and Patterns: Code/Unit Testing Principles, Practices, and Patterns.md
  - Trade:
    - Best Losers Wins: Trade/Best Losers Wins.md
    - How I made 2M in the Stock Market: Trade/How I made 2M in the Stock Market.md
    - How Legendary Traders Made Millions: Trade/How Legendary Traders Made Millions.md
    - How to Trade in Stocks: Trade/How to Trade in Stocks.md
    - Secrets For Profiting in Bull and Bear Markets: Trade/Secrets For Profiting in Bull and Bear Markets.md
    - The Battle for Investment Survival: Trade/The Battle for Investment Survival.md
    - The Perfect Speculator: Trade/The Perfect Speculator.md
    - The Perfect Stock: Trade/The Perfect Stock.md
    - Think and Trade like a Champion: Trade/Think and Trade like a Champion.md
    - Trade Like a Stock Market Wizard: Trade/Trade Like a Stock Market Wizard.md
    - Trade Your Way to Financial Freedom: Trade/Trade Your Way to Financial Freedom.md
  - Fantasy:
    - Animal Farm: Fantasy/AnimalFarm.md
    - Blood Over Bright Haven: Fantasy/Blood Over Bright Haven.md
    - Dune: Fantasy/Dune.md
    - Elantris: Fantasy/Elantris.md
    - Gentleman Bastard: Fantasy/Gentleman Bastard.md
    - 1984: Fantasy/1984.md
    - Harry Potter: Fantasy/Harry Potter.md
    - Mistborn: Fantasy/Mistborn.md
    - The Kingkiller Chronicle: Fantasy/The Kingkiller Chronicle.md
    - The Night Circus: Fantasy/The Night Circus.md
    - The Cruel Prince: Fantasy/The Cruel Prince.md
    - The Hunger Games: Fantasy/The Hunger Games.md
    - The First Law: Fantasy/The First Law.md
    - The Folk of the Air: Fantasy/The Folk of the Air.md
    - The Poppy War: Fantasy/The Poppy War.md
    - The Red Rising Saga: Fantasy/The Red Rising Saga.md
    - The Rithmatist: Fantasy/The Rithmatist.md
    - The Stormlight Archive: Fantasy/The Stormlight Archieve.md
    - The Wheel of Time: Fantasy/The Wheel of Time.md
    - Throne of Glass: Fantasy/Throne of Glass.md
    - Six of Crows: Fantasy/Six of Crows.md
    - Spinning Silver: Fantasy/Spinning Silver.md
    - Uprooted: Fantasy/Uprooted.md
    - Warbreaker: Fantasy/Warbreaker.md
  - Science Fiction:
    - Flowers for Algernon: Science Fiction/Flowers for Algernon.md
    - Jurassic Park: Science Fiction/Jurassic Park.md
    - Old Man's War: Science Fiction/Old Man's War.md
    - Bobiverse: Science Fiction/Bobiverse.md
    - Divergent: Science Fiction/Divergent.md
    - Ender's Saga: Science Fiction/Ender's Saga.md
    - Skyward: Science Fiction/Skyward.md
    - Snow Crash: Science Fiction/Snow Crash.md
    - The Giver: Science Fiction/The Giver.md
    - The Martian: Science Fiction/The Martian.md
    - Ready Player One: Science Fiction/Ready Player One.md
    - Recursion: Science Fiction/Recursion.md
  - Fiction:
    - To Kill a Mockingbird: Fiction/To Kill a Mockingbird.md
    - A Gentleman in Moscow: Fiction/A Gentleman in Moscow.md
    - A Little Princess: Fiction/A Little Princess.md
    - A Count of Monte Cristo: Fiction/A Count of Monte Cristo.md
    - A Thousand Splendid Suns: Fiction/A Thousand Splendid Suns.md
    - Anne of Green Gables: Fiction/Anne of Green Gables.md
    - Eleanor Oliphant is completely Fine: Fiction/Eleanor Oliphant is completely Fine.md
    - Finding Audrey: Fiction/Finding Audrey.md
    - The Girl with the Dragon Tattoo: Fiction/The Girl with the Dragon Tatto.md
    - Little Fires Everywhere: Fiction/Little Fires Everywhere.md
    - Normal People: Fiction/Normal People.md
    - The Book Thief: Fiction/The Book Thief.md
    - The Kite Runner: Fiction/The Kite Runner.md
  - Philosophy:
    - The Art of War: Philosophy/The Art of War.md
    - Ikigai: Philosophy/Ikigai.md
    - Letters from a stoic: Philosophy/Letters from a stoic.md
    - Man's Search for Meaning: Philosophy/Man's Search for Meaning.md
    - Sapiens: Philosophy/Sapiens.md
  - Romance:
    - Attachments: Romance/Attachments.md
    - Five Feet Apart: Romance/Five Feet Apart.md
    - Me Before You: Romance/Me Before You.md
    - The bookish life of Nina Hill: Romance/The bookish life of Nina Hill.md
    - The Fault in Our Stars: Romance/The Fault in Our Stars.md
    - The Flatshare: Romance/The Flatshare.md
    - The Hating Game: Romance/The Hating Game.md
    - The Kiss Quotient: Romance/The Kiss Quotient.md
    - The Kiss Thief: Romance/The Kiss Thief.md

# Theme
theme:
  name: material
  logo: assets/favicon.png
  favicon: assets/favicon.png
  # Palette toggle for dark mode
  palette:
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
          icon: material/brightness-4
          name: Switch to light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
          icon: material/brightness-7
          name: Switch to dark mode
  features:
    - content.action.edit # Allows "Edit on GitHub" links
    - content.action.view # Allows "View on GitHub" links
    - content.code.copy # Allows code blocks to have a copy button
    - navigation.path # Enables path navigation top of docs for smaller screens
    - navigation.tabs # Enables tabbed navigation
    - navigation.indexes # Enables attachment of sub section index 
  icon:
    repo: fontawesome/brands/git-alt 
    edit: material/pencil 
    view: material/eye

# Extensions
markdown_extensions:
  - admonition # for Callout boxes
  - pymdownx.highlight: 
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex: # for rendering math equations
      generic: true
  - def_list # List extensions
  - pymdownx.tasklist: # List extensions
      custom_checkbox: true

# Copyright
copyright: Copyright &copy; 2025 Nodes Automations

# Footer social links
extra:
  generator: false # remove "Generated with MkDocs" footer