# Site settings
site_name: Books
site_url: https://vivekkpatel.github.io/Books/
use_directory_urls: false
# Navigation Tree
nav:
  - Home:
    - index.md
  - Self Help:
    - Factfulness: Self Help/Factfulness.md
    - How to Win Friends and Influence People: Self Help/How to Win Friends and Influence People.md
    - Letters from a stoic: Self Help/Letters from a stoic.md
    - Man's Search for Meaning: Self Help/Man's Search for Meaning.md
    - Quiet The Power of Introverts: Self Help/Quiet The Power of Introverts.md
    - The Obstacle Is the Way: Self Help/The Obstacle Is the Way.md
    - Why We Sleep : Self Help/Why We Sleep.md
  - Biography:
    - Adventures of a Curious Character: Biography/Adventures of a Curious Character.md
    - Alibaba: Biography/Alibaba.md
    - Bad Blood: Biography/Bad Blood.md
    - Bricklin on Technology: Biography/Bricklin on Technology.md
    - Educated: Biography/Educated.md
    - Hard Drive: Biography/Hard Drive.md
    - Just for Fun: Biography/Just for Fun.md
    - Know My Name A Memoir: Biography/Know My Name A Memoir.md
    - Masters of Doom: Biography/Masters of Doom.md
    - My Life An Illustrated Biography: Biography/My Life An Illustrated Biography.md
    - My Life: Biography/My Life.md
    - Nikola Tesla: Biography/Nikola Tesla.md
    - Permanent Record: Biography/Permanent Record.md
    - Sam Walton Made In America: Biography/Sam Walton Made In America.md
    - Shoe Dog: Biography/Shoe Dog.md
    - Steve Jobs: Biography/Steve Jobs.md
    - The Glass Castle: Biography/The Glass Castle.md
    - The Upstarts: Biography/The Upstarts.md
    - Wild: Biography/Wild.md
  - Business:
    - Anything You Want: Business/Anything You Want.md
    - Design Your Work: Business/Design Your Work.md
    - Let's Talk Money: Business/Let's Talk Money.md
    - Never Split the Difference: Business/Never Split the Difference.md
    - Rich Dad, Poor Dad: Business/Rich Dad, Poor Dad.md
    - The Richest Man in Babylon: Business/The Richest Man in Babylon.md
    - The Zurich Axioms: Business/The Zurich Axioms.md
    - Zero to One: Business/Zero to One.md
  - Code:
    - A Beginner's Guide to AutoHotkey: Code/A Beginner's Guide to AutoHotkey.md
    - AutoCAD 2012 DXF reference: Code/AutoCAD 2012 DXF reference.md
    - AutoCAD Platform Customization VBA: Code/AutoCAD Platform Customization VBA.md
    - AutoHotkey Applications: Code/AutoHotkey Applications.md
    - Computational Engineering: Code/Computational Engineering.md
    - Digging Deeper into AutoHotkey: Code/Digging Deeper into AutoHotkey.md
    - Start Programming in NET for AutoCAD: Code/Start Programming in NET for AutoCAD.md
    - The Markdown Guide: Code/The Markdown Guide.md
    - The Pragamatic Programmer: Code/The Pragamatic Programmer.md
  - Trade:
    - Best Losers Wins: Trade/Best Losers Wins.md
    - How to Trade in Stocks: Trade/How to Trade in Stocks.md
  - Fantasy:
    - Blood Over Bright Haven: Fantasy/Blood Over Bright Haven.md
  - Science Fiction:
    - Flowers for Algernon: Science Fiction/Flowers for Algernon.md
    - Start Programming in NET for AutoCAD: Code/Start Programming in NET for AutoCAD.md
    - The Markdown Guide: Code/The Markdown Guide.md
    - The Pragamatic Programmer: Code/The Pragamatic Programmer.md
  - Fantasy:
    - Blood Over Bright Haven: Fantasy/Blood Over Bright Haven.md
  - Science Fiction:
    - Flowers for Algernon: Science Fiction/Flowers for Algernon.md

# Theme
theme:
  name: material
  logo: assets/favicon.png
  favicon: assets/favicon.png
  # Palette toggle for dark mode
  palette:
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
          icon: material/brightness-4
          name: Switch to light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
          icon: material/brightness-7
          name: Switch to dark mode
  features:
    - content.action.edit # Allows "Edit on GitHub" links
    - content.action.view # Allows "View on GitHub" links
    - content.code.copy # Allows code blocks to have a copy button
    - navigation.path # Enables path navigation top of docs for smaller screens
    - navigation.tabs # Enables tabbed navigation
    - navigation.indexes # Enables attachment of sub section index 
  icon:
    repo: fontawesome/brands/git-alt 
    edit: material/pencil 
    view: material/eye

# Extensions
markdown_extensions:
  - admonition # for Callout boxes
  - pymdownx.highlight: 
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex: # for rendering math equations
      generic: true
  - def_list # List extensions
  - pymdownx.tasklist: # List extensions
      custom_checkbox: true

# Copyright
copyright: Copyright &copy; 2025 Nodes Automations

# Footer social links
extra:
  generator: false # remove "Generated with MkDocs" footer
  social:
    - icon: fontawesome/solid/globe
      link: www.nodesautomations.com
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/NodesAutomations
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/vivekpatel-nodesautomations/
    - icon: fontawesome/brands/github
      link: https://github.com/orgs/NodesAutomations


